package models.domain

import java.text.{ NumberFormat, DateFormat }
import java.time.{ Instant, ZoneId, ZonedDateTime }
import java.time.format.DateTimeFormatter
import java.util.UUID

/** An Expense is just a record of spending something at some time
 *
 *  @param amountInCents The amount spent, in USD Cents
 *  @param name An identifier
 *  @param dateOccured The UTC Epoch timestamp (in seconds) when this expense occured
 *  @param expenseId A UUID uniquely identifying this transaction. Optional parameter, a randomUUID will be generated by default
 */
case class Expense(val amountInCents: Long, val name: String, val dateOccured: Long, val expenseId: UUID = UUID.randomUUID())
