language: scala

scala:
  - 2.11.8

script: sbt ++$TRAVIS_SCALA_VERSION test

jdk:
  - oraclejdk8

services:
  - mysql

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS accountable_test;'

env:
  global:
    - MYSQL_TEST_USER="travis"
    - MYSQL_TEST_PASSWORD=""

